# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import spin10_pb2 as spin10__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spin10_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuantumGatewayStub:
    """Quantum gateway service SHZ Spin10
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Simulate = channel.unary_unary(
                '/spin10.QuantumGateway/Simulate',
                request_serializer=spin10__pb2.SimulationRequest.SerializeToString,
                response_deserializer=spin10__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.StreamSimulate = channel.unary_stream(
                '/spin10.QuantumGateway/StreamSimulate',
                request_serializer=spin10__pb2.SimulationRequest.SerializeToString,
                response_deserializer=spin10__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/spin10.QuantumGateway/Health',
                request_serializer=spin10__pb2.Empty.SerializeToString,
                response_deserializer=spin10__pb2.HealthResponse.FromString,
                _registered_method=True)


class QuantumGatewayServicer:
    """Quantum gateway service SHZ Spin10
    """

    def Simulate(self, request, context):
        """Single-request MERA simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSimulate(self, request, context):
        """Result streaming (progress + final result)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Compute cluster health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantumGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Simulate': grpc.unary_unary_rpc_method_handler(
                    servicer.Simulate,
                    request_deserializer=spin10__pb2.SimulationRequest.FromString,
                    response_serializer=spin10__pb2.SimulationResponse.SerializeToString,
            ),
            'StreamSimulate': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSimulate,
                    request_deserializer=spin10__pb2.SimulationRequest.FromString,
                    response_serializer=spin10__pb2.SimulationResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=spin10__pb2.Empty.FromString,
                    response_serializer=spin10__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spin10.QuantumGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spin10.QuantumGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuantumGateway:
    """Quantum gateway service SHZ Spin10
    """

    @staticmethod
    def Simulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spin10.QuantumGateway/Simulate',
            spin10__pb2.SimulationRequest.SerializeToString,
            spin10__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSimulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/spin10.QuantumGateway/StreamSimulate',
            spin10__pb2.SimulationRequest.SerializeToString,
            spin10__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spin10.QuantumGateway/Health',
            spin10__pb2.Empty.SerializeToString,
            spin10__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
