# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spin10.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'spin10.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cspin10.proto\x12\x06spin10\"\xa5\x01\n\x11SimulationRequest\x12\x10\n\x08priority\x18\x01 \x01(\x05\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x39\n\x08metadata\x18\x03 \x03(\x0b\x32\'.spin10.SimulationRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"z\n\x12SimulationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\x03\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\x01\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x12\n\nlatency_ms\x18\x06 \x01(\x01\"K\n\x0eHealthResponse\x12\x17\n\x0fray_initialized\x18\x01 \x01(\x08\x12\x0f\n\x07healthy\x18\x02 \x01(\x08\x12\x0f\n\x07version\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\xcf\x01\n\x0eQuantumGateway\x12\x41\n\x08Simulate\x12\x19.spin10.SimulationRequest\x1a\x1a.spin10.SimulationResponse\x12I\n\x0eStreamSimulate\x12\x19.spin10.SimulationRequest\x1a\x1a.spin10.SimulationResponse0\x01\x12/\n\x06Health\x12\r.spin10.Empty\x1a\x16.spin10.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spin10_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMULATIONREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_SIMULATIONREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SIMULATIONREQUEST']._serialized_start=25
  _globals['_SIMULATIONREQUEST']._serialized_end=190
  _globals['_SIMULATIONREQUEST_METADATAENTRY']._serialized_start=143
  _globals['_SIMULATIONREQUEST_METADATAENTRY']._serialized_end=190
  _globals['_SIMULATIONRESPONSE']._serialized_start=192
  _globals['_SIMULATIONRESPONSE']._serialized_end=314
  _globals['_HEALTHRESPONSE']._serialized_start=316
  _globals['_HEALTHRESPONSE']._serialized_end=391
  _globals['_EMPTY']._serialized_start=393
  _globals['_EMPTY']._serialized_end=400
  _globals['_QUANTUMGATEWAY']._serialized_start=403
  _globals['_QUANTUMGATEWAY']._serialized_end=610
# @@protoc_insertion_point(module_scope)
